[package]
name = "sapp-console-log"
version = "0.1.0"
authors = ["Duane Johnson <duane.johnson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
miniquad = "0.2.10"